export const BASE_URL = "https://apihub.kma.go.kr";

export const ENDPOINTS = [
  {
    id: "asos_hourly_time",
    title: "ASOS hourly observation at time",
    category: "surface_observation",
    path: "/api/typ01/url/kma_sfctm2.php",
    format: "text",
    requiredParams: ["authKey"],
    optionalParams: ["tm", "stn", "help"],
    defaultParams: { tm: "202211300900", stn: "108", help: "1" },
  },
  {
    id: "asos_hourly_range",
    title: "ASOS hourly observation range",
    category: "surface_observation",
    path: "/api/typ01/url/kma_sfctm3.php",
    format: "text",
    requiredParams: ["authKey"],
    optionalParams: ["tm1", "tm2", "stn", "help"],
    defaultParams: { tm1: "201512110100", tm2: "201512110300", stn: "108", help: "1" },
  },
  {
    id: "asos_daily_date",
    title: "ASOS daily observation at date",
    category: "surface_observation",
    path: "/api/typ01/url/kma_sfcdd.php",
    format: "text",
    requiredParams: ["authKey"],
    optionalParams: ["tm", "stn", "disp", "help"],
    defaultParams: { tm: "20150715", stn: "108", disp: "0", help: "1" },
  },
  {
    id: "asos_daily_range",
    title: "ASOS daily observation range",
    category: "surface_observation",
    path: "/api/typ01/url/kma_sfcdd3.php",
    format: "text",
    requiredParams: ["authKey"],
    optionalParams: ["tm", "tm1", "tm2", "obs", "stn", "help", "mode"],
    defaultParams: { tm1: "20151211", tm2: "20151214", stn: "108", help: "1" },
  },
  {
    id: "asos_element",
    title: "ASOS element query",
    category: "surface_observation",
    path: "/api/typ01/url/kma_sfctm5.php",
    format: "text",
    requiredParams: ["authKey"],
    optionalParams: ["tm1", "tm2", "obs", "stn", "disp", "help"],
    defaultParams: { tm2: "201504060900", obs: "TA", stn: "108", disp: "0", help: "1" },
  },
  {
    id: "surface_normals",
    title: "Surface climate normals",
    category: "surface_normals",
    path: "/api/typ01/url/sfc_norm1.php",
    format: "text",
    requiredParams: ["authKey", "norm", "tmst"],
    optionalParams: ["stn", "MM1", "DD1", "MM2", "DD2"],
    defaultParams: { norm: "D", tmst: "2021", stn: "108", MM1: "5", DD1: "1", MM2: "5", DD2: "2" },
  },
  {
    id: "year_summary",
    title: "Surface yearly summary",
    category: "surface_yearbook",
    path: "/api/typ02/openApi/SfcYearlyInfoService/getYearSumry",
    format: "xml_or_json",
    requiredParams: ["authKey", "year"],
    optionalParams: ["pageNo", "numOfRows", "dataType"],
    defaultParams: { pageNo: "1", numOfRows: "1", dataType: "JSON", year: "2016" },
  },
  {
    id: "year_summary2",
    title: "Surface yearly summary 2",
    category: "surface_yearbook",
    path: "/api/typ02/openApi/SfcYearlyInfoService/getYearSumry2",
    format: "xml_or_json",
    requiredParams: ["authKey", "year"],
    optionalParams: ["pageNo", "numOfRows", "dataType"],
    defaultParams: { pageNo: "1", numOfRows: "1", dataType: "JSON", year: "2016" },
  },
  {
    id: "avg_ta_anomaly",
    title: "Average temperature anomaly",
    category: "surface_yearbook",
    path: "/api/typ02/openApi/SfcYearlyInfoService/getAvgTaAnamaly",
    format: "xml_or_json",
    requiredParams: ["authKey", "year"],
    optionalParams: ["pageNo", "numOfRows", "dataType"],
    defaultParams: { pageNo: "1", numOfRows: "1", dataType: "JSON", year: "2016" },
  },
  {
    id: "rainfall_anomaly",
    title: "Rainfall anomaly",
    category: "surface_yearbook",
    path: "/api/typ02/openApi/SfcYearlyInfoService/getRnAnamaly",
    format: "xml_or_json",
    requiredParams: ["authKey", "year"],
    optionalParams: ["pageNo", "numOfRows", "dataType"],
    defaultParams: { pageNo: "1", numOfRows: "1", dataType: "JSON", year: "2016" },
  },
  {
    id: "station_phenomenon_data",
    title: "Station phenomenon data",
    category: "surface_yearbook",
    path: "/api/typ02/openApi/SfcYearlyInfoService/getStnPhnmnData",
    format: "xml_or_json",
    requiredParams: ["authKey", "year", "station"],
    optionalParams: ["pageNo", "numOfRows", "dataType"],
    defaultParams: { pageNo: "1", numOfRows: "1", dataType: "JSON", year: "2016", station: "140" },
  },
  {
    id: "station_phenomenon_data2",
    title: "Station phenomenon data 2",
    category: "surface_yearbook",
    path: "/api/typ02/openApi/SfcYearlyInfoService/getStnPhnmnData2",
    format: "xml_or_json",
    requiredParams: ["authKey", "year", "station"],
    optionalParams: ["pageNo", "numOfRows", "dataType"],
    defaultParams: { pageNo: "1", numOfRows: "1", dataType: "JSON", year: "2016", station: "140" },
  },
  {
    id: "station_phenomenon_data3",
    title: "Station phenomenon data 3",
    category: "surface_yearbook",
    path: "/api/typ02/openApi/SfcYearlyInfoService/getStnPhnmnData3",
    format: "xml_or_json",
    requiredParams: ["authKey", "year", "station"],
    optionalParams: ["pageNo", "numOfRows", "dataType"],
    defaultParams: { pageNo: "1", numOfRows: "1", dataType: "JSON", year: "2016", station: "140" },
  },
  {
    id: "monthly_note",
    title: "Surface monthly report note",
    category: "surface_monthly_report",
    path: "/api/typ02/openApi/SfcMtlyInfoService/getNote",
    format: "xml_or_json",
    requiredParams: ["authKey", "year", "month"],
    optionalParams: ["pageNo", "numOfRows", "dataType"],
    defaultParams: { pageNo: "1", numOfRows: "1", dataType: "JSON", year: "2016", month: "09" },
  },
  {
    id: "monthly_station_list",
    title: "Surface monthly station list",
    category: "surface_monthly_report",
    path: "/api/typ02/openApi/SfcMtlyInfoService/getSfcStnLstTbl",
    format: "xml_or_json",
    requiredParams: ["authKey", "year", "month"],
    optionalParams: ["pageNo", "numOfRows", "dataType"],
    defaultParams: { pageNo: "1", numOfRows: "1", dataType: "JSON", year: "2016", month: "09" },
  },
  {
    id: "monthly_summary",
    title: "Surface monthly summary",
    category: "surface_monthly_report",
    path: "/api/typ02/openApi/SfcMtlyInfoService/getMmSumry",
    format: "xml_or_json",
    requiredParams: ["authKey", "year", "month"],
    optionalParams: ["pageNo", "numOfRows", "dataType"],
    defaultParams: { pageNo: "1", numOfRows: "1", dataType: "JSON", year: "2016", month: "09" },
  },
  {
    id: "monthly_summary2",
    title: "Surface monthly summary 2",
    category: "surface_monthly_report",
    path: "/api/typ02/openApi/SfcMtlyInfoService/getMmSumry2",
    format: "xml_or_json",
    requiredParams: ["authKey", "year", "month"],
    optionalParams: ["pageNo", "numOfRows", "dataType"],
    defaultParams: { pageNo: "1", numOfRows: "1", dataType: "JSON", year: "2016", month: "09" },
  },
  {
    id: "monthly_daily_weather",
    title: "Daily weather data in monthly report",
    category: "surface_monthly_report",
    path: "/api/typ02/openApi/SfcMtlyInfoService/getDailyWthrData",
    format: "xml_or_json",
    requiredParams: ["authKey", "year", "month", "station"],
    optionalParams: ["pageNo", "numOfRows", "dataType"],
    defaultParams: { pageNo: "1", numOfRows: "1", dataType: "JSON", year: "2016", month: "09", station: "90" },
  },
  {
    id: "graphic_surface_phenomenon",
    title: "Graphic surface weather phenomenon",
    category: "surface_graphic",
    path: "/api/typ03/php/alw/sfc/sfc_ww_pnt.php",
    format: "image",
    requiredParams: ["authKey", "obs", "tm"],
    optionalParams: ["val", "stn", "obj", "map", "grid", "legend", "size", "itv", "zoom_level", "zoom_x", "zoom_y", "gov"],
    defaultParams: {
      obs: "ww_sfc",
      tm: "202212221120",
      val: "1",
      stn: "1",
      obj: "mq",
      map: "HR",
      grid: "2",
      legend: "1",
      size: "600",
      itv: "5",
      zoom_level: "0",
      zoom_x: "0000000",
      zoom_y: "0000000",
      gov: "",
    },
  },
];

export function findEndpoint(endpointId) {
  return ENDPOINTS.find((endpoint) => endpoint.id === endpointId);
}
